Traceback (most recent call last):
  File ".\start.py", line 22, in <module>
    os.path('''''''''''')
TypeError: 'module' object is not callable
